dataset:
  class_names: ['Angry', 'Disgust', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']

training:
  num_classes: 7
  image_size: 224
  grayscale: true
  pretrained: true

test:
  ckpt : "/mnt/hdd/home/tawheed/Documents/Programming/Emotion Detector/AffectSense/server/FER/best_model.pth"